spring.application.name=movie_api


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=false

##Configure cache to use caffeine
spring.cache.type=caffeine
## configure settings
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m
##to get needed logs once our app change or communicate with local db
spring.jpa.show-sql=true

jwt.secret=ThisIsAVerySecretKeyThatIsAtLeast32CharactersLong
jwt.expiration=3600000